{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Database\",\"ServerName\",\"DatabaseName\",\"Sales\",\"Products\",\"Dates\",\"Customer\",\"Store\",\"RowLimiter\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Database",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases ( ServerName ){[Name = DatabaseName]}[Data],",
          "    KeepViewsOnly = Table.SelectRows ( Source, each [Kind] = \"View\" )",
          "in",
          "    KeepViewsOnly"
        ],
        "kind": "m",
        "lineageTag": "6359e611-22f9-48a8-8f83-6af3e77d2fff",
        "queryGroup": "Params"
      },
      {
        "name": "ServerName",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"SUMMER\\SQL2022\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7017da56-1e89-4184-b951-3244a2c9f114",
        "queryGroup": "Params"
      },
      {
        "name": "DatabaseName",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"Contoso 5M\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "94e27c98-c860-4ec7-b623-1464891c9a47",
        "queryGroup": "Params"
      },
      {
        "name": "RowLimiter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "-1 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4089163d-4edc-4060-9d7a-14ca3a701844",
        "queryGroup": "Params"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Params"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Queries that are to be loaded to the data model",
        "folder": "Model Queries"
      }
    ],
    "relationships": [
      {
        "name": "453d438c-e820-47a3-95d4-28e3a9c89ead",
        "fromColumn": "Order Date",
        "fromTable": "Sales",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "de52d7ee-f28c-438f-9eba-041d62c1c890",
        "fromColumn": "Delivery Date",
        "fromTable": "Sales",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "61330f2d-60e1-4004-beed-c79381ce7965",
        "fromColumn": "ProductKey",
        "fromTable": "Sales",
        "toColumn": "ProductKey",
        "toTable": "Products"
      },
      {
        "name": "7704a9a1-cacc-433e-b510-256fdf97dd69",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "a4ba6ff7-7170-4754-a655-07dbdc8e9dc3",
        "fromColumn": "StoreKey",
        "fromTable": "Sales",
        "toColumn": "StoreKey",
        "toTable": "Store"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddaf3c0e-2da8-43ad-8cd5-9bb28032d228",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed985ded-29b1-4093-86a0-61ce3fe81acd",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Birthday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d5222e1b-fc01-47b3-8728-4759afb5b5b7",
            "sourceColumn": "Birthday",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30248cb7-e92a-49e6-a851-ba34d131dd9f",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c98087f-35b8-473d-b131-3cdf56b4a208",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d931e79-6ec9-453b-a8c4-ba21a220357e",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Country Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "baec6dfc-ccc3-4fa8-b78d-0136b07cabb2",
            "sourceColumn": "Country Code",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00811a34-6992-4acf-89f3-e1d40558a4af",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f59bffe2-024c-4e79-a263-75745a5b5498",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "089580ed-5f3e-4e23-8f76-cc7c2036dbe9",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c32e45ee-6b55-4689-864c-8a7f2559ed16",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "State Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63472154-f83f-4b17-baa0-9d12166d7797",
            "sourceColumn": "State Code",
            "summarizeBy": "none"
          },
          {
            "name": "Zip Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4895a5e-5162-4842-89d4-e94d12b9f612",
            "sourceColumn": "Zip Code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c5fe7db1-36b2-4994-ad27-db4030e91fa8",
        "partitions": [
          {
            "name": "Customer-8224e87d-404a-4bbd-96d4-9a748f3e6147",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Customer\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "c2aa5d46-c675-4d57-85d4-ed272e269c45",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae685ba0-470d-4672-9a42-79b0d6032633",
            "sourceColumn": "Day of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99155343-e77e-4c96-9611-d57389180c8b",
            "sourceColumn": "Day of Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2668dc97-c03a-45f3-84a2-05791f9aa1a9",
            "sourceColumn": "Day of Week Short",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fde013b7-cfa7-4200-98cc-6544dcfee9c6",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50569896-af63-4638-b53e-add092479881",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f7f8a43-ad0f-416e-87bb-c4284f4195c3",
            "sourceColumn": "Month Short",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbafcea2-54ef-42a8-b07a-4d0cdfd1eef5",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Working Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6a957df1-2af1-483a-b029-0b305e6e7649",
            "sourceColumn": "Working Day",
            "summarizeBy": "none"
          },
          {
            "name": "Working Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6437148c-c491-4c57-afd9-89b426b8054b",
            "sourceColumn": "Working Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9ed5946-6fe0-4ce3-891d-b2c3e652b173",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9191199-b5db-4315-a3e1-c576f00bc249",
            "sourceColumn": "Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87f2547f-6a57-44e0-9426-bf2735b82a68",
            "sourceColumn": "Year Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66369ace-3d22-40c8-8ae3-820fc4a173b2",
            "sourceColumn": "Year Month Short",
            "summarizeBy": "none"
          },
          {
            "name": "Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42884faa-b0ae-4b04-89c5-f3fb6bcb3014",
            "sourceColumn": "Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d7f4583-f895-44fc-9c3e-6a489cdf33eb",
            "sourceColumn": "Year Quarter Number",
            "summarizeBy": "sum"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "2fb20bc1-9223-49cf-bd49-f1ea78068d9e",
        "partitions": [
          {
            "name": "Dates-3eae6ff9-ee18-4fd5-8f0f-b9c8bb39b332",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Date\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10d8761d-5e21-4d3f-8428-67439328fc17",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2653ed2-7668-438e-9d32-ccc26e45f8fc",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Category Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97d457d7-0a24-456f-acab-eb8ec1d983ee",
            "sourceColumn": "Category Code",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8330230-8bdc-4316-968d-642aa5b228f9",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5cd1ac8-bb15-43b3-af79-cdfa6c21dc66",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "Product Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c404cff-9bab-4f08-9c1b-fad1f006c2e1",
            "sourceColumn": "Product Code",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74391824-f9d6-4a87-ad0a-402326b8cff8",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb0727a4-a6a5-46f9-88ce-1033219b776f",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7705c03-28e3-4d25-92dc-d27aef5aee51",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a493072-339c-422f-8eaa-115ba3191234",
            "sourceColumn": "Subcategory Code",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "07febb22-264c-44f4-b6f4-90f0309c2b9e",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cdbbe035-6a68-4871-b126-7e1723fe0037",
            "sourceColumn": "Unit Price",
            "summarizeBy": "none"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7cfad905-f229-4f39-8470-808660bab471",
            "sourceColumn": "Weight",
            "summarizeBy": "none"
          },
          {
            "name": "Weight Unit Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d10061a1-fd7f-44f5-89e2-c01417111f00",
            "sourceColumn": "Weight Unit Measure",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b15c3fbd-334c-4e2e-80f2-e452fec05d18",
        "partitions": [
          {
            "name": "Products-518dc289-3c14-4afb-9ffb-16dae88df2e2",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Product\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d54af21c-d8b7-4e68-863a-edaae9999898",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9da81248-b7e0-4d7d-9b48-791c757fa12e",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Net Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "657133f3-8195-4706-aa31-3588f637452e",
            "sourceColumn": "Net Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0455a63f-acf8-424c-b512-e04e546571b8",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3a94314-e694-4807-b4ae-6898b9fd2452",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a285d988-81d0-48df-abda-0a87c50d8e52",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b3cb452-0385-4b3c-802f-7c31a2154f0b",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6b4d84c1-3ec7-4d3b-9a71-7d22cdf71b19",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7e4fe7b6-fc8c-440f-a2ba-32c8a8750f29",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "449f5b21-3ca5-4850-a22d-e02fb6cd014f",
        "measures": [
          {
            "name": "Sales Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "01 - Model Measures",
            "expression": [
              "",
              "SUMX ( ",
              "    Sales,",
              "    Sales[Quantity] * Sales[Net Price]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6b79d766-9d2f-40e2-a754-ca5e7815ceaf"
          },
          {
            "name": "Cost Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "01 - Model Measures",
            "expression": [
              "",
              "SUMX ( ",
              "    Sales,",
              "    Sales[Quantity] * Sales[Unit Cost]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "1a05b01b-e590-40fb-a7ee-4565871b6ed5"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "01 - Model Measures",
            "expression": "[Sales Amount] - [Cost Amount]",
            "formatString": "#,0",
            "lineageTag": "0161a754-14c9-4ddf-8b88-a618f1624045"
          },
          {
            "name": "Margin %",
            "displayFolder": "01 - Model Measures",
            "expression": "DIVIDE ( [Profit], [Sales Amount] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec3fce0e-26f4-481b-9345-e37a55d35df3"
          },
          {
            "name": "Total Quantity",
            "displayFolder": "01 - Model Measures",
            "expression": "SUM ( Sales[Quantity] )",
            "formatString": "#,0",
            "lineageTag": "99923f88-4771-4c02-bb1a-ccd071fab868"
          }
        ],
        "partitions": [
          {
            "name": "Sales-0276af6a-9cd7-48d4-98ba-8646a154570c",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Sales\"]}[Data],",
                "    RemoveHighCardinalityColumns = Table.SelectColumns(Source,{\"Order Date\", \"Delivery Date\", \"CustomerKey\", \"StoreKey\", \"ProductKey\", \"Quantity\", \"Unit Price\", \"Net Price\", \"Unit Cost\"}),",
                "    LimitRows = if RowLimiter = -1 then RemoveHighCardinalityColumns else Table.FirstN ( RemoveHighCardinalityColumns, RowLimiter )",
                "in",
                "    LimitRows"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Store",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Close Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "00fe8453-3bc3-40d9-ab8f-0f984ec0d26c",
            "sourceColumn": "Close Date",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c685302b-df22-4168-acb2-8bebe65b1fe8",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e3f7659-9cca-4e5c-9ed3-c984dfe0c6ec",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Open Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "312ef6f6-1bc3-4bec-8775-5cc61be28c8c",
            "sourceColumn": "Open Date",
            "summarizeBy": "none"
          },
          {
            "name": "Square Meters",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95ab86ce-295d-4b02-b61e-23a390c763e5",
            "sourceColumn": "Square Meters",
            "summarizeBy": "sum"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db65230f-7ed9-4dee-9906-33861852a5bc",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3933d266-cb92-4154-8f0d-5ec5c94c0f12",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Store Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2b992ea8-3b01-4603-ae1a-973517145a76",
            "sourceColumn": "Store Code",
            "summarizeBy": "count"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3819789-2d3d-4421-8f16-b001f6d3cd48",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9efca987-d64d-4147-ac68-382608b47f06",
        "partitions": [
          {
            "name": "Store-468ab332-909a-498f-bc51-372c50bf31b3",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Store\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}