{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Database\",\"ServerName\",\"DatabaseName\",\"Sales\",\"Products\",\"Dates\",\"Customer\",\"Store\",\"RowLimiter\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Database",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Databases ( ServerName ){[Name = DatabaseName]}[Data],",
          "    KeepViewsOnly = Table.SelectRows ( Source, each [Kind] = \"View\" )",
          "in",
          "    KeepViewsOnly"
        ],
        "kind": "m",
        "lineageTag": "6359e611-22f9-48a8-8f83-6af3e77d2fff",
        "queryGroup": "Params"
      },
      {
        "name": "ServerName",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"SUMMER\\SQL2022\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7017da56-1e89-4184-b951-3244a2c9f114",
        "queryGroup": "Params"
      },
      {
        "name": "DatabaseName",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"Contoso 5M\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "94e27c98-c860-4ec7-b623-1464891c9a47",
        "queryGroup": "Params"
      },
      {
        "name": "RowLimiter",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "100000 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4089163d-4edc-4060-9d7a-14ca3a701844",
        "queryGroup": "Params"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Params"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Queries that are to be loaded to the data model",
        "folder": "Model Queries"
      }
    ],
    "relationships": [
      {
        "name": "a3602dc8-f8e7-4a91-8535-77713af8c2ec",
        "fromColumn": "Date",
        "fromTable": "Dates",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_98e687f4-1048-4558-aa5b-8dc77100d969"
      },
      {
        "name": "23b04e29-753f-4153-a035-fec2094625fe",
        "fromColumn": "Birthday",
        "fromTable": "Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4aef60cf-f134-47d5-b94a-121d431d7170"
      },
      {
        "name": "4f5882bb-dfd8-4104-90ea-1a8614f5aa82",
        "fromColumn": "Open Date",
        "fromTable": "Store",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_89ca0dda-f605-474d-ac58-dcfa3489ef95"
      },
      {
        "name": "5ac18f8b-aefe-4d11-a3b1-34b6dc096d75",
        "fromColumn": "Close Date",
        "fromTable": "Store",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2326e2c0-d862-4668-a556-b1e6d65f2fef"
      },
      {
        "name": "453d438c-e820-47a3-95d4-28e3a9c89ead",
        "fromColumn": "Order Date",
        "fromTable": "Sales",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "de52d7ee-f28c-438f-9eba-041d62c1c890",
        "fromColumn": "Delivery Date",
        "fromTable": "Sales",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "61330f2d-60e1-4004-beed-c79381ce7965",
        "fromColumn": "ProductKey",
        "fromTable": "Sales",
        "toColumn": "ProductKey",
        "toTable": "Products"
      },
      {
        "name": "7704a9a1-cacc-433e-b510-256fdf97dd69",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "a4ba6ff7-7170-4754-a655-07dbdc8e9dc3",
        "fromColumn": "StoreKey",
        "fromTable": "Sales",
        "toColumn": "StoreKey",
        "toTable": "Store"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddaf3c0e-2da8-43ad-8cd5-9bb28032d228",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed985ded-29b1-4093-86a0-61ce3fe81acd",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Birthday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d5222e1b-fc01-47b3-8728-4759afb5b5b7",
            "sourceColumn": "Birthday",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4aef60cf-f134-47d5-b94a-121d431d7170"
                },
                "isDefault": true,
                "relationship": "23b04e29-753f-4153-a035-fec2094625fe"
              }
            ]
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30248cb7-e92a-49e6-a851-ba34d131dd9f",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c98087f-35b8-473d-b131-3cdf56b4a208",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d931e79-6ec9-453b-a8c4-ba21a220357e",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Country Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "baec6dfc-ccc3-4fa8-b78d-0136b07cabb2",
            "sourceColumn": "Country Code",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00811a34-6992-4acf-89f3-e1d40558a4af",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f59bffe2-024c-4e79-a263-75745a5b5498",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "089580ed-5f3e-4e23-8f76-cc7c2036dbe9",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c32e45ee-6b55-4689-864c-8a7f2559ed16",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "State Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63472154-f83f-4b17-baa0-9d12166d7797",
            "sourceColumn": "State Code",
            "summarizeBy": "none"
          },
          {
            "name": "Zip Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4895a5e-5162-4842-89d4-e94d12b9f612",
            "sourceColumn": "Zip Code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c5fe7db1-36b2-4994-ad27-db4030e91fa8",
        "partitions": [
          {
            "name": "Customer-8224e87d-404a-4bbd-96d4-9a748f3e6147",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Customer\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_0a8243f4-108f-4a1f-869f-51cbd4b6108d",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4883f707-7fcb-4c9a-9304-9d6d2e624ab2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "664217fd-b7e9-452f-816d-2bcc7cb482e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c2889d3-efef-4b27-b32b-985d8de8ec71",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e139cf0d-a9d1-40ef-9985-4f97fa471973",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "27afac7c-ba3d-445c-8492-9a85a7406ab1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7722fee2-b87b-4644-a79b-93808d40379e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e52a1126-1805-4608-9d3e-3687b851d2ed",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "63870937-6a00-46ef-95e1-c429025f549c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7fd694d7-12d7-4aa8-9135-b2a3a5d97e8f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d7ef78d3-a147-4ddd-875a-42afc88091a9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e34dea09-a313-442d-9d4d-9453b7c35056",
                "ordinal": 3
              }
            ],
            "lineageTag": "59580698-741f-472f-842c-53b1c9d0f3ee"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a11ac2b2-a5bb-4580-995e-b01fa357e493",
        "partitions": [
          {
            "name": "DateTableTemplate_0a8243f4-108f-4a1f-869f-51cbd4b6108d-f3df1f6d-1f37-48cd-8182-3a9d95c3051d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c2aa5d46-c675-4d57-85d4-ed272e269c45",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_98e687f4-1048-4558-aa5b-8dc77100d969"
                },
                "isDefault": true,
                "relationship": "a3602dc8-f8e7-4a91-8535-77713af8c2ec"
              }
            ]
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae685ba0-470d-4672-9a42-79b0d6032633",
            "sourceColumn": "Day of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99155343-e77e-4c96-9611-d57389180c8b",
            "sourceColumn": "Day of Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2668dc97-c03a-45f3-84a2-05791f9aa1a9",
            "sourceColumn": "Day of Week Short",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fde013b7-cfa7-4200-98cc-6544dcfee9c6",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50569896-af63-4638-b53e-add092479881",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f7f8a43-ad0f-416e-87bb-c4284f4195c3",
            "sourceColumn": "Month Short",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbafcea2-54ef-42a8-b07a-4d0cdfd1eef5",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Working Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6a957df1-2af1-483a-b029-0b305e6e7649",
            "sourceColumn": "Working Day",
            "summarizeBy": "none"
          },
          {
            "name": "Working Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6437148c-c491-4c57-afd9-89b426b8054b",
            "sourceColumn": "Working Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9ed5946-6fe0-4ce3-891d-b2c3e652b173",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9191199-b5db-4315-a3e1-c576f00bc249",
            "sourceColumn": "Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87f2547f-6a57-44e0-9426-bf2735b82a68",
            "sourceColumn": "Year Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66369ace-3d22-40c8-8ae3-820fc4a173b2",
            "sourceColumn": "Year Month Short",
            "summarizeBy": "none"
          },
          {
            "name": "Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42884faa-b0ae-4b04-89c5-f3fb6bcb3014",
            "sourceColumn": "Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d7f4583-f895-44fc-9c3e-6a489cdf33eb",
            "sourceColumn": "Year Quarter Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2fb20bc1-9223-49cf-bd49-f1ea78068d9e",
        "partitions": [
          {
            "name": "Dates-3eae6ff9-ee18-4fd5-8f0f-b9c8bb39b332",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Date\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2326e2c0-d862-4668-a556-b1e6d65f2fef",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "262bf9c6-f905-4bed-8105-f5b0b8a2c904",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d6e44c44-2c91-465e-b7e1-7bac71b86cdc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e524a4c4-a04f-47f6-9eb0-d13a9cd04956",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ceaa0291-e762-490e-a86a-e043247cfafa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "61bc6f05-65ce-4a56-96cc-0d4cb9bc41cf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8fbf574e-0874-4bdb-9fa2-8b043d2b93b6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5e5b4f9c-b0d2-4486-9c60-57e5f317a84c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "dfa0bdcd-1a8e-4ec8-b357-42cbef2fc129",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1de0cbb2-5e4f-41ed-b0db-bce0c8cd7c26",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1e52266a-e38d-4654-a391-4a4f1e8427b1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cece99bf-62ce-433e-9ce9-f847f3690cc3",
                "ordinal": 3
              }
            ],
            "lineageTag": "3a493004-a282-43ce-8576-7df0f2d9693f"
          }
        ],
        "isHidden": true,
        "lineageTag": "103bac48-64cb-4909-ba76-30cf934a0adc",
        "partitions": [
          {
            "name": "LocalDateTable_2326e2c0-d862-4668-a556-b1e6d65f2fef-a4a0af79-b176-4727-a31a-c67edc400d56",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Store'[Close Date])), 1, 1), Date(Year(MAX('Store'[Close Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4aef60cf-f134-47d5-b94a-121d431d7170",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "48dbdd83-d919-4fcc-8747-15ffc6bc0e14",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "30c2c058-af4c-4013-aa36-56b0ccea9b87",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ee5728e8-fd99-4f36-a587-6636113300c8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8892568e-7c22-4e56-987e-3c87b7a04d1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "39ae8891-0d1b-4659-82fc-0954b32b7dfc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "22637316-59cb-4dc4-abc1-3a00f274b061",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "67983b3a-9ccd-4af4-9d4e-57bdf9746c54",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bb089964-b329-4f4f-8c5d-91eb43037ac0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fb6ee980-30a8-4684-a702-f3627e448434",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "dc159212-dd55-4e23-8efa-0e83a976e1c2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6b4fc3fc-2039-4d9c-a36f-87fbf5876e81",
                "ordinal": 3
              }
            ],
            "lineageTag": "553cffbe-dde7-4aeb-8bee-3b7696004bc4"
          }
        ],
        "isHidden": true,
        "lineageTag": "4859c7fe-3822-42f6-860e-b9eeea3b3218",
        "partitions": [
          {
            "name": "LocalDateTable_4aef60cf-f134-47d5-b94a-121d431d7170-c409045f-81e5-4b15-91bf-7a32779b8c5f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer'[Birthday])), 1, 1), Date(Year(MAX('Customer'[Birthday])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_89ca0dda-f605-474d-ac58-dcfa3489ef95",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "10a6ee19-145e-44a8-9f22-ef78b1133fe1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "efd13086-0762-4267-b482-f64b477bb289",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ca4a776a-b23d-4f1c-974d-ef9672fdaf04",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "88fd543c-5ff8-4885-951e-a0baf564ea24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "34a46d96-84fc-4329-be90-8a63335b288d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "672e193b-a25e-45d5-9cc4-426aaa839b22",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5343dbf4-c948-464b-ae4f-60d10bfcfcb0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5dc0601f-9bf3-42c1-9206-dbfee8c84bb3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "12671a19-f28b-40df-bc6a-2134184397c8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5b7e5f33-7602-4900-a7c6-e4c4083535a0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6455ea85-af02-4f68-993a-4a2e53cfa6e4",
                "ordinal": 3
              }
            ],
            "lineageTag": "0ed12eb2-ffad-4e46-92ae-0d4165fa1d38"
          }
        ],
        "isHidden": true,
        "lineageTag": "d339fa57-4a4e-4e79-8edf-f70a509d239e",
        "partitions": [
          {
            "name": "LocalDateTable_89ca0dda-f605-474d-ac58-dcfa3489ef95-6e98e75c-14f8-4167-bc5d-06c3b3d05cb2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Store'[Open Date])), 1, 1), Date(Year(MAX('Store'[Open Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_98e687f4-1048-4558-aa5b-8dc77100d969",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "653b0afc-102c-4dd8-82f5-a0b41efd9958",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1d278771-299d-4fc0-bea8-50984bcfa64a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e9d9e85c-609c-4ddc-8590-0049dea0c749",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e83cf07e-43bb-4b20-ae54-64f5d9c7985d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ad90aaae-d4ab-40ef-928e-a190930acf85",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dcda9741-6029-481a-b09d-d2a48b15c83c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abd13707-1c29-4066-b940-c0934dda924e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "da063957-ba77-47f1-958e-2ae443668f63",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e4f2e9f9-92c4-4818-8442-3684b6cb9d4d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f17cff22-552f-4c19-91d5-84d39bf2bb23",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6a2bb321-0d08-455d-af4a-72b487774cd6",
                "ordinal": 3
              }
            ],
            "lineageTag": "0d9b3e5f-8e0e-4ce7-b22f-0f0918ed8ffa"
          }
        ],
        "isHidden": true,
        "lineageTag": "6015a3e1-a3fb-4174-9796-32e97170ffe3",
        "partitions": [
          {
            "name": "LocalDateTable_98e687f4-1048-4558-aa5b-8dc77100d969-4efcbf40-96c5-43db-84d1-041a1635f3f5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dates'[Date])), 1, 1), Date(Year(MAX('Dates'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10d8761d-5e21-4d3f-8428-67439328fc17",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2653ed2-7668-438e-9d32-ccc26e45f8fc",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Category Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97d457d7-0a24-456f-acab-eb8ec1d983ee",
            "sourceColumn": "Category Code",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8330230-8bdc-4316-968d-642aa5b228f9",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5cd1ac8-bb15-43b3-af79-cdfa6c21dc66",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "Product Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c404cff-9bab-4f08-9c1b-fad1f006c2e1",
            "sourceColumn": "Product Code",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74391824-f9d6-4a87-ad0a-402326b8cff8",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb0727a4-a6a5-46f9-88ce-1033219b776f",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7705c03-28e3-4d25-92dc-d27aef5aee51",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a493072-339c-422f-8eaa-115ba3191234",
            "sourceColumn": "Subcategory Code",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "07febb22-264c-44f4-b6f4-90f0309c2b9e",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cdbbe035-6a68-4871-b126-7e1723fe0037",
            "sourceColumn": "Unit Price",
            "summarizeBy": "none"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7cfad905-f229-4f39-8470-808660bab471",
            "sourceColumn": "Weight",
            "summarizeBy": "none"
          },
          {
            "name": "Weight Unit Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d10061a1-fd7f-44f5-89e2-c01417111f00",
            "sourceColumn": "Weight Unit Measure",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b15c3fbd-334c-4e2e-80f2-e452fec05d18",
        "partitions": [
          {
            "name": "Products-518dc289-3c14-4afb-9ffb-16dae88df2e2",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Product\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Currency Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46530a82-ccac-4730-95f5-2b8a6fc64531",
            "sourceColumn": "Currency Code",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d54af21c-d8b7-4e68-863a-edaae9999898",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9da81248-b7e0-4d7d-9b48-791c757fa12e",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Exchange Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fdf304f6-f515-47b4-a843-7fc79efcb113",
            "sourceColumn": "Exchange Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Line Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c8c2a860-db1b-46eb-886c-dce07c9e9c83",
            "sourceColumn": "Line Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "657133f3-8195-4706-aa31-3588f637452e",
            "sourceColumn": "Net Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0455a63f-acf8-424c-b512-e04e546571b8",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "Order Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46e619c5-43be-454b-9e32-22a09a8d4ba7",
            "sourceColumn": "Order Number",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3a94314-e694-4807-b4ae-6898b9fd2452",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a285d988-81d0-48df-abda-0a87c50d8e52",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b3cb452-0385-4b3c-802f-7c31a2154f0b",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6b4d84c1-3ec7-4d3b-9a71-7d22cdf71b19",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7e4fe7b6-fc8c-440f-a2ba-32c8a8750f29",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "449f5b21-3ca5-4850-a22d-e02fb6cd014f",
        "measures": [
          {
            "name": "Sales Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "01 - Model Measures",
            "expression": [
              "",
              "SUMX ( ",
              "    Sales,",
              "    Sales[Quantity] * Sales[Net Price]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6b79d766-9d2f-40e2-a754-ca5e7815ceaf"
          },
          {
            "name": "Cost Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "01 - Model Measures",
            "expression": [
              "",
              "SUMX ( ",
              "    Sales,",
              "    Sales[Quantity] * Sales[Unit Cost]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "1a05b01b-e590-40fb-a7ee-4565871b6ed5"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "01 - Model Measures",
            "expression": "[Sales Amount] - [Cost Amount]",
            "formatString": "#,0",
            "lineageTag": "0161a754-14c9-4ddf-8b88-a618f1624045"
          },
          {
            "name": "Margin %",
            "displayFolder": "01 - Model Measures",
            "expression": "DIVIDE ( [Profit], [Sales Amount] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec3fce0e-26f4-481b-9345-e37a55d35df3"
          },
          {
            "name": "Total Quantity",
            "displayFolder": "01 - Model Measures",
            "expression": "SUM ( Sales[Quantity] )",
            "formatString": "#,0",
            "lineageTag": "99923f88-4771-4c02-bb1a-ccd071fab868"
          }
        ],
        "partitions": [
          {
            "name": "Sales-0276af6a-9cd7-48d4-98ba-8646a154570c",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Sales\"]}[Data],",
                "    LimitRows = if RowLimiter = -1 then Source else Table.FirstN ( Source, RowLimiter )",
                "in",
                "    LimitRows"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Store",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Close Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "00fe8453-3bc3-40d9-ab8f-0f984ec0d26c",
            "sourceColumn": "Close Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2326e2c0-d862-4668-a556-b1e6d65f2fef"
                },
                "isDefault": true,
                "relationship": "5ac18f8b-aefe-4d11-a3b1-34b6dc096d75"
              }
            ]
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c685302b-df22-4168-acb2-8bebe65b1fe8",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e3f7659-9cca-4e5c-9ed3-c984dfe0c6ec",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Open Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "312ef6f6-1bc3-4bec-8775-5cc61be28c8c",
            "sourceColumn": "Open Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_89ca0dda-f605-474d-ac58-dcfa3489ef95"
                },
                "isDefault": true,
                "relationship": "4f5882bb-dfd8-4104-90ea-1a8614f5aa82"
              }
            ]
          },
          {
            "name": "Square Meters",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95ab86ce-295d-4b02-b61e-23a390c763e5",
            "sourceColumn": "Square Meters",
            "summarizeBy": "sum"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db65230f-7ed9-4dee-9906-33861852a5bc",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3933d266-cb92-4154-8f0d-5ec5c94c0f12",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Store Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2b992ea8-3b01-4603-ae1a-973517145a76",
            "sourceColumn": "Store Code",
            "summarizeBy": "count"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3819789-2d3d-4421-8f16-b001f6d3cd48",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9efca987-d64d-4147-ac68-382608b47f06",
        "partitions": [
          {
            "name": "Store-468ab332-909a-498f-bc51-372c50bf31b3",
            "mode": "import",
            "queryGroup": "Model Queries",
            "source": {
              "expression": [
                "let",
                "    Source = Database{[Name = \"Store\"]}[Data]",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}